create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  invoice_no text not null unique,
  invoice_date date not null default current_date,
  customer_name text not null,
  customer_mobile text,
  customer_address text,
  customer_gst text,
  total_amount numeric(12,2) not null default 0,
  payment_mode text,
  cash_amount numeric(12,2) default 0,
  online_amount numeric(12,2) default 0,
  invoice_pdf_url text,
  invoice_file_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  laptop_id bigint null references public.laptop_tests(id) on delete set null,
  machine_code text,
  serial_no text,
  model text,
  cpu text,
  generation text,
  ram text,
  storage text,
  price numeric(12,2) default 0,
  item_type text default 'laptop',
  description text,
  quantity integer default 1,
  unit_price numeric(12,2) default 0,
  line_total numeric(12,2) default 0,
  is_complimentary boolean default false,
  created_at timestamptz not null default now()
);

alter table public.sales
  add column if not exists invoice_pdf_url text,
  add column if not exists invoice_file_path text,
  add column if not exists finance_dp_amount numeric(12,2) default 0,
  add column if not exists installment_count integer default 0,
  add column if not exists dp_payment_mode text,
  add column if not exists partial_dp_cash_amount numeric(12,2),
  add column if not exists partial_dp_online_amount numeric(12,2),
  add column if not exists payment_narration text;

alter table public.sales_items
  add column if not exists item_type text default 'laptop',
  add column if not exists description text,
  add column if not exists quantity integer default 1,
  add column if not exists unit_price numeric(12,2) default 0,
  add column if not exists line_total numeric(12,2) default 0,
  add column if not exists is_complimentary boolean default false,
  add column if not exists graphic_card text;

alter table public.transfers
  add column if not exists sale_invoice_id bigint null references public.sales(id) on delete set null;

alter table public.transfers
  drop constraint if exists transfers_sale_invoice_id_fkey;

alter table public.transfers
  add constraint transfers_sale_invoice_id_fkey
  foreign key (sale_invoice_id)
  references public.sales(id)
  on delete set null;

alter table public.sales enable row level security;
alter table public.sales_items enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'sales'
      and policyname = 'sales_authenticated_all'
  ) then
    create policy sales_authenticated_all
    on public.sales
    for all
    to authenticated
    using (true)
    with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'sales_items'
      and policyname = 'sales_items_authenticated_all'
  ) then
    create policy sales_items_authenticated_all
    on public.sales_items
    for all
    to authenticated
    using (true)
    with check (true);
  end if;
end $$;

insert into storage.buckets (id, name, public)
select 'invoices', 'invoices', true
where not exists (
  select 1 from storage.buckets where id = 'invoices'
);

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'invoice_bucket_authenticated_select'
  ) then
    create policy invoice_bucket_authenticated_select
    on storage.objects
    for select
    to authenticated
    using (bucket_id = 'invoices');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'invoice_bucket_authenticated_insert'
  ) then
    create policy invoice_bucket_authenticated_insert
    on storage.objects
    for insert
    to authenticated
    with check (bucket_id = 'invoices');
  end if;
end $$;

create table if not exists public.sales_payments (
  id bigint generated by default as identity primary key,
  sale_id bigint null references public.sales(id) on delete set null,
  customer_name text,
  customer_mobile text,
  payment_date date not null default current_date,
  amount numeric(12,2) not null default 0,
  payment_mode text,
  remarks text,
  created_at timestamptz not null default now()
);

create index if not exists sales_payments_sale_id_idx
  on public.sales_payments(sale_id);

create index if not exists sales_payments_customer_mobile_idx
  on public.sales_payments(customer_mobile);

create index if not exists sales_payments_payment_date_idx
  on public.sales_payments(payment_date);

alter table public.sales_payments enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'sales_payments'
      and policyname = 'sales_payments_authenticated_all'
  ) then
    create policy sales_payments_authenticated_all
    on public.sales_payments
    for all
    to authenticated
    using (true)
    with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'invoice_bucket_authenticated_update'
  ) then
    create policy invoice_bucket_authenticated_update
    on storage.objects
    for update
    to authenticated
    using (bucket_id = 'invoices')
    with check (bucket_id = 'invoices');
  end if;
end $$;
